### ISSUE TITLE
[FORM ĐĂNG KÝ TIÊM] Lỗi chức năng "Sử dụng thông tin trước"

### ISSUE THREAD

**Issue by chuthithuy** [VietOpenCPS/Vaccom#19]
Bước 1: Đăng ký tiêm thành công
Bước 2: Click "Sử dụng thông tin trước"
Kết quả: Hệ thống chưa fill các dữ liệu từ phiếu đăng ký thành công trước đó.
Yêu cầu: Cho fill thông tin  từ phiếu đăng ký thành công trước đó.

**Comment by congtrinh0209** [comment]
Chỉ lưu các thông tin chung như địa chỉ,...
