### ISSUE TITLE
[FORM Đăng ký tiêm] Dùng Enter để chuyển sang trường tiếp theo

### ISSUE THREAD

**Issue by chuthithuy** [VietOpenCPS/Vaccom#8]
Xem xét phương án Dùng Enter để chuyển sang trường tiếp theo thay vì chế độ mặc định là Tab (thao tác lâu hơn).

**Comment by congtrinh0209** [comment]
Đã fix

**Comment by tuanta** [comment]
Nên có thông tin là issue được fix trong (những) commit cụ thể nào.
